#pragma once

//#define CONFIG_CONSOLE_USED
#define CONFIG_LOGS_FILE_USED

//#define CONFIG_CHECK_PKT_ID_LOST_USED

#define CONFIG_PAGE_SYSTEMCONFIG_USED
#define CONFIG_PAGE_TEST_USED
//#define CONFIG_PAGE_DEBUG_USED

